### ISSUE TITLE
window 10 compile with gcc, missing core.cpp

### ISSUE THREAD

**Issue by gshields** [spieglt/FlyingCarpet#11]
cd E:\ghs\go\src\github.com\therecipe\qt\core
TERM='dumb' g++ -I "E:\\ghs\\go\\src\\github.com\\therecipe\\qt\\core" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=c:\\tmp\\go-build451990318\\b124=/tmp/go-build" -gno-record-gcc-switches -I "c:\\tmp\\go-build451990318\\b124\\" -g -O2 -o "c:\\tmp\\go-build451990318\\b124\\_x003.o" -c core.cpp
# github.com/therecipe/qt/core
core.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
compilation terminated.

**Comment by spieglt** [comment]
Did you encounter this error when running `wg_rebuild.ps1`? Did you run `qtsetup` as part of the setup of `github.com/therecipe/qt/core`? Did it complete successfully?
