### ISSUE TITLE
Add Ctrl-Q quit hotkey

### ISSUE THREAD

**Issue by tutacat** [spieglt/FlyingCarpet#17]

**Comment by spieglt** [comment]
This is probably doable but I don't know if it's worth the effort. What OS are you on? Can you use the standard Alt-F4 on Windows, Ctrl-W on Linux, or Command-Q on Mac?

**Comment by tutacat** [comment]
Ctrl-W is normally only added by the program itself, instead of the window manager. Alt-F4 is not universally added to Linux window managers either

**Comment by spieglt** [comment]
Good point, I'll put this on the list.

**Comment by spieglt** [comment]
@tutacat I got folder upload and some other stuff done, and version 4.1 is on the [releases](https://github.com/spieglt/flyingcarpet/releases) page! Please let me know what you think if you try it out, and thanks again for the recommendations.
