### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by frol** [spieglt/FlyingCarpet#2]
*FlyingCarpet is already an awesome project! Thank you!*

I only miss Linux support... Is it planned?

**Comment by spieglt** [comment]
Thank you for the feedback! Did you try it/did it work? And yes, I do plan on extending it for Linux but probably not for a couple months.

**Comment by frol** [comment]
I cannot test it at the moment since most of my devices are running on Linux, but I'll give it a try as soon as I have access to Win/Mac laptops.

BTW, it seems that there is a design limitation to laptops since FlyingCarpet works only on desktop OSes and require WiFi module, which drops both desktop stations, which are usually connected via cable, and mobile devices, which run on mobile OSes...

**Comment by spieglt** [comment]
It's still rough around the edges and I only have Linux Mint 18 to test on, but there is a working Linux binary in /bin of the `linux` branch! Please try it and let me know if you can.
