### ISSUE TITLE
Doesn't work on the M1

### ISSUE THREAD

**Issue by taoeffect** [spieglt/FlyingCarpet#25]
```
$ ./flyingcarpet_cli_mac_apple_silicon_arm64 -peer mac -receive .
Welcome to Flying Carpet!

Starting Transfer
=============================
Transfer password: EojJKY
Please use this password on sending end when prompted to start transfer.
=============================

2022-03-25 18:03:55.335 flyingcarpet_cli_mac_apple_silicon_arm64[14946:333559] startAdHoc error: Error Domain=com.apple.coreWLAN.error Code=-3930 "(null)"
Failed to start ad hoc network
Aborting transfer.
```

**Comment by spieglt** [comment]
This isn't an M1 issue, but rather a Mac-to-Mac issue that I mention in the readme: ```Flying Carpet no longer works between two Macs if the receiving end is running Big Sur because Apple deprecated the necessary ad hoc WiFi functions. Use AirDrop instead. Mac-to-Windows and Mac-to-Linux still work as the Linux or Windows side will always host the network.```
Link to Apple docs: https://developer.apple.com/documentation/corewlan/cwinterface/1426417-startibssmode. Sorry about that!
