### ISSUE TITLE
Any Plan For Android Version ?

### ISSUE THREAD

**Issue by Its-Satyajit** [spieglt/FlyingCarpet#26]
Any Plan For Android Version ?

**Comment by spieglt** [comment]
Yes but I have to learn Kotlin and Android development first so it'll be a bit.

**Comment by spieglt** [comment]
Hi @Its-Satyajit, the Android version is ready but is awaiting approval for the Google Play Store. If you don't mind sideloading, you can download `android_FlyingCarpet.apk` from the [releases](https://github.com/spieglt/flyingcarpet/releases) page.

**Comment by spieglt** [comment]
The Android version is available on the [Play Store](https://play.google.com/store/apps/details?id=dev.spiegl.flyingcarpet).
