### ISSUE TITLE
Is there a way to get android apk while it is in review?

### ISSUE THREAD

**Issue by psuzn** [spieglt/FlyingCarpet#34]
Thank you for the Android version, I have been really looking forward to it. Is there a way to get the android apk while it is in review?

**Comment by spieglt** [comment]
Yes! Just added `android_FlyingCarpet.apk` to the [releases](https://github.com/spieglt/flyingcarpet/releases) page. It's not signed and I didn't build it on my usual machine so it may not work but try it out and let me know. Can fix in the next few days if it doesn't work.

**Comment by psuzn** [comment]
Thanks, I'm unable to install maybe because it is not signed.

**Comment by spieglt** [comment]
Ah, sorry about that, I just removed that version and uploaded a signed one.

**Comment by spieglt** [comment]
I just successfully downloaded the new version from Github and installed on a test device. Had to hit `More details` and `Install anyway`. You may have to adjust a setting or two on your phone to allow installing apps from outside the Play Store.

**Comment by psuzn** [comment]
Got it installed, thank you for the good work.

**Comment by spieglt** [comment]
Fantastic, thank you for following up! Please let me know if it works on your devices if you get the chance. Very gratifying to hear someone was excited about the release.
