### ISSUE TITLE
Help installing on MacOs

### ISSUE THREAD

**Issue by pablichjenkov** [spieglt/FlyingCarpet#36]
Hey man thank you so much for this work.
How can I get the version for MacOs?

**Comment by spieglt** [comment]
You're welcome! Go to the [releases](https://github.com/spieglt/FlyingCarpet/releases) page and download `macOS_FlyingCarpet_7.0.0_universal.dmg`.

**Comment by pablichjenkov** [comment]
Ahh, I see. Thanks
