### ISSUE TITLE
How to build this project for Android?

### ISSUE THREAD

**Issue by r4ve1** [spieglt/FlyingCarpet#39]
Really interested in Tauri & this project. 
I've tried this command:
```
cargo tauri build -t aarch64-linux-android 
```
But the openssl-sys dependency failed to build. What is the official build steps for the Android platform? Need some help plz :)

**Comment by spieglt** [comment]
Thanks for your interest! The Android version is available on the [Google Play Store](https://play.google.com/store/apps/details?id=dev.spiegl.flyingcarpet). It's written in Kotlin and the code is not public. The desktop Tauri version would not work on Android even if you compiled it.
