### ISSUE TITLE
Dependency to libwebkitgtk3 cant be met in Arch based Manjaro

### ISSUE THREAD

**Issue by schlypel** [spieglt/FlyingCarpet#4]
... as the title says, there appears to be no package that would supply me with the required package.
The error that occurs while starting up is:

`./Flying Carpet: error while loading shared libraries: libwebkitgtk-3.0.so.0: cannot open shared object file: No such file or directory`

But nevertheless, I think this is an awesome idea and would make a useful addition to any Computer/OS :)
Thanks for your work

**Comment by spieglt** [comment]
Yep, currently only supporting on Debian as I only have one Linux machine to test with. Would you be interested in trying the CLI version? It may work as it doesn't require the graphics libraries, though you will need `nmcli`. It's here if so, please let me know if you try: https://github.com/spieglt/FlyingCarpet/releases/download/v1.2/flyingcarpet.Linux.CLI.zip
Thanks for your interest!

**Comment by schlypel** [comment]
Opening a receive connection worked on manjaro.

Only my other computer was a linux headless server running debian, and there the missing nmcli prevented any further testing.

But in general, the cli appears to be working.

```
./flyingcarpet -receive ./ -peer linux
=============================
Transfer password: 4PZP
Please use this password on sending end when prompted to start transfer.
=============================

exit status 2
exit status 10
exit status 10
exit status 10
exit status 10
Listening on :3290
```

Will check on debian based distro some time in the future.
Thanks

**Comment by spieglt** [comment]
Thanks and please let me know if you get it working or if there's anything else I can do to help. May eventually switch out `nmcli` with `iw`.
