### ISSUE TITLE
Cant open scanner

### ISSUE THREAD

**Issue by Leobai** [spieglt/FlyingCarpet#40]
Please restart transfer. Failed to scan QR code: com.google.mlkit.common.MlKitException: Code scanner module is not supported on current Google Play Services version, please upgrade.

**Comment by Leobai** [comment]
solved

**Comment by qazhub** [comment]
How did you solve this?

**Comment by Leobai** [comment]
update to the latest google play service

**Comment by qazhub** [comment]
Sadly not all phones have Google Play service installed :(

**Comment by spieglt** [comment]
Yep, unfortunately Google's QR code viewer requires Play Services and it doesn't work on some devices. I link to this https://issuetracker.google.com/issues/261579118 in the readme. On the devices I've been able to test, deleting Play Services' data and letting it download again fixes the issue: https://support.google.com/googleplay/answer/9037938.

**Comment by spieglt** [comment]
If anyone has a better QR code scanner Kotlin library to recommend, please do and I'll look into replacing it.
