### ISSUE TITLE
no module downloaded

### ISSUE THREAD

**Issue by Leobai** [spieglt/FlyingCarpet#41]
Please restart transfer. Failed to scan QR code: com.google.mlkit.common.MlKitException: Waiting for the Barcode UI module to be downloaded.

**Comment by spieglt** [comment]
Was this fixed once it downloaded?

**Comment by spieglt** [comment]
Closing this as I assume it worked once the Barcode UI module downloaded again. That's been my experience.

**Comment by Leobai** [comment]
it is fixed already. thanks a lot
