### ISSUE TITLE
Restore Licensing

### ISSUE THREAD

**Issue by Starz0r** [spieglt/FlyingCarpet#42]
Currently, the repository has no `LICENSE` file, which it had previously. One could assume that the code is still licensed under the previous BSD 3-Clause, as that was the last license text to exist in the repository. But legally, that wouldn't fly, so if possible, could we get a license in the repository again?

**Comment by spieglt** [comment]
Yes, thanks for the reminder. I'm not sure which license I want to apply to this version though now that the Android and iOS versions exist. May I ask about your use case/desired features?

**Comment by Ziqi-Yang** [comment]
Made a [AUR package](https://aur.archlinux.org/packages/flying-carpet-bin) for it. It's better to have a license.

**Comment by spieglt** [comment]
I added the GPL3. Will consider adding a line to the readme about separate licensing.
