### ISSUE TITLE
ios software

### ISSUE THREAD

**Issue by beichen123-hub** [spieglt/FlyingCarpet#43]
Why should the version of ios be higher than ios15.5 to be used, and can't be used below this version

**Comment by spieglt** [comment]
I don't remember why that was chosen, but it looks like the App Store might allow lower versions. I can go down to iOS 14.2 without breaking the code. What version would you like to use it with?

**Comment by spieglt** [comment]
@beichen123-hub May I ask what version you need to use? I might close this issue soon if I don't hear from you.

**Comment by spieglt** [comment]
If anyone sees this later, let me know what version of iOS you're trying to use and I'll look into it.

**Comment by sintien** [comment]
I use 15.8.3 (only way for me to copy files from Android to iPhone). Can you support this iOS version? It is jailbroken and I can sideload an ipa
