### ISSUE TITLE
Android version installation fails

### ISSUE THREAD

**Issue by firstrose** [spieglt/FlyingCarpet#44]
It says error while parsing the apk.
Any clue?

**Comment by spieglt** [comment]
Not off the top of my head unfortunately. Any more information you can provide?

**Comment by spieglt** [comment]
I just successfully installed https://github.com/spieglt/FlyingCarpet/releases/download/v7.1/android_FlyingCarpet.apk on a test device. What Android version are you on? Have you tried installing from the [Play Store](https://play.google.com/store/apps/details?id=dev.spiegl.flyingcarpet)?

**Comment by firstrose** [comment]
Which version does it support?

I have two devices. One is Android10, the other one is HarmonyOS 3.0 with android compatible layer. Both fails.

Google play store is not available in PRC, so your apk is the only choice.

Thanks.

**Comment by spieglt** [comment]
Ah, okay, I think I should be able to make a version for Android 10. I'll try that later tonight and let you know. Currently the minimum version is Android 11.

**Comment by firstrose** [comment]
@spieglt 

Thank you for your kindness.
But are you sure Android 10 is the minimal version **required by your code** ?
Is it possible to modify compiling setting (without change code) for more terget version ?

**Comment by spieglt** [comment]
I had to change the code a bit but was able to lower the API level to 21, Android 5.0. I need help testing it on devices older than Android 11 though, please try [`android_FlyingCarpet_api_21.apk`](https://github.com/spieglt/FlyingCarpet/releases/download/v7.1/android_FlyingCarpet_api_21.apk) from the [releases](https://github.com/spieglt/FlyingCarpet/releases) page and let me know if it works.

**Comment by firstrose** [comment]
The new apk installs ok on Android10. But can not operate.

Send action:

After select a file, the soft gives an error.

![Screenshot_2023-06-29-09-08-52-847_dev spiegl flyingcarpet](https://github.com/spieglt/FlyingCarpet/assets/1551595/c00ed52a-6fc1-471f-a312-043e8b36db9f)

Looks like that you're using the latest Android features. Aha.

Receive action:

The soft ask me to select a folder. After selecting, soft returned to the main activity and **crashes**. Is there any log file?

Thanks

**Comment by spieglt** [comment]
I found a place where the code was too new for API 21, so have replaced that APK with `android_FlyingCarpet_api_23.apk` with 23 as the minimum API version. I'm not sure how to fix the fact that your phone needs a newer version of Play Services to use the barcode scanner unfortunately. I could add a manual method of password entry but it would take some time.

**Comment by firstrose** [comment]
Excuse me. Are you meaning you are using Play Service to scan/generate barcodes?
IMHO, why not use ZXing directly? I found your apk already includes it.

**Comment by spieglt** [comment]
Correct, I’m using Google’s official barcode scanner: https://developers.google.com/ml-kit/vision/barcode-scanning/code-scanner. It has been unpleasant to work with and requires a workaround on many devices, so you’re probably right that I should use ZXing instead. Right now ZXing is just used to generate QR codes.

**Comment by spieglt** [comment]
Please download and try https://github.com/spieglt/FlyingCarpet/releases/download/v7.1/android_FlyingCarpet_api_24.apk and let me know if it works. I replaced the Play Services scanner with https://github.com/journeyapps/zxing-android-embedded. Minimum API is now 24.

**Comment by spieglt** [comment]
I changed it slightly to allow portrait orientation when scanning the QR code.

**Comment by firstrose** [comment]
version 24 tested on Android 10. Still trying android to android.

Send:

After selecting a file, it asks for camera permission, then to scan a barcode. Looks ok.

Receive:

Select a folder, grant permission, and still crashes without messages.

Thanks

**Comment by spieglt** [comment]
Hmm, sorry to hear it's still not receiving. Sounds somewhat like https://github.com/spieglt/FlyingCarpet/issues/45 though I haven't heard what settings needed to be changed there. After it requests permissions for the folder, if it's hosting the hotspot (which it would be when receiving from Android), it should request permission to start the hotspot, start the hotspot, generate the QR code, and then wait for the TCP connection. I will look into making a build with more debug messages. Thank you for helping troubleshoot.

**Comment by firstrose** [comment]
I am sorry for provided incomplete information.

1. 1st device is MIUI 12.5.1(Android 10)

MIUI is a hacked system by Xiaomi.

I looked over #45, without knowing what is the setting. But I leaved a message to xiqishow.

I tried again on it, found the app says it's starting hotspot before crash. The message is flashing fast, so I didn't noticed it before.

2. 2nd device is Huawei Harmony OS 3.0, compatible with Android 10(at least cpu-z said so)

It's also crashed when starting hotspot.

Thank you for your patience.

**Comment by spieglt** [comment]
Ah, okay, sounds like it can't start the hotspot... The "Started hotspot" message means the hotspot API was called, but asynchronously, so that message can print before the hotspot actually starts. It uses https://developer.android.com/guide/topics/connectivity/localonlyhotspot, which I would think wouldn't work in another OS like Harmony. I'm not sure about MIUI, but I'll see what I can find online. I may work on adding some more debug logging but not sure when.

**Comment by firstrose** [comment]
Thank you for your time.

I looked documents of HarmonyOS, and found articles about wifi.

https://developer.harmonyos.com/en/docs/documentation/doc-guides/connectivity-wlan-overview-0000000000030016

Will it be helpful?

MIUI is a problem, I didn't find documents yet. Maybe I need some time. 

Could you write debug info into a file? So I can submit the log to them and ask for the right doing.

**Comment by spieglt** [comment]
Unfortunately it looks like HarmonyOS doesn't support Google's LocalOnlyHotspot API. I've haven't been able to find anything about MIUI either. Will let you know on debug logging, should have a chance to work on it soon.

**Comment by spieglt** [comment]
Thanks for the information @BingoKingo. Based on what I've read so far, it seems unlikely to me that the LocalOnlyHotspot API will work on MIUI. I'm not sure why it would throw a permission error when trying to open a socket either.

**Comment by spieglt** [comment]
Closing this as it's been determined that Xaomi devices, MIUI, and HarmonyOS won't work with Flying Carpet.

**Comment by nyreed** [comment]
Just to add some more confusion to the situation, the app _does_ seem to work on my device.

Redmi Note 10 Pro - MIUI 14 Custom 'Xiaomi.eu' community rom, which is Android 13. 
  
So I'm not sure if this is something which eventually got supported in MIUI, or if it's something to do with the custom ROM.  
  
But LocalOnlyHotspot seems to work!
  
I wonder if anyone on a more recent stock MIUI rom can test?

**Comment by spieglt** [comment]
@nyreed Huh, wild, thanks for letting me know. Maybe has something to do with that ROM? Did you use one of the APKs from the releases page or download from the Play Store?

**Comment by nyreed** [comment]
I installed the latest apk from the release page. (android_FlyingCarpet_8.0.0.apk).  
  
But I appear to be able to download it from Play Store too, and that works just fine to transfer files too.
