### ISSUE TITLE
Ubuntu 20.04 ?

### ISSUE THREAD

**Issue by ludetie** [spieglt/FlyingCarpet#46]
Hello,

On Ubuntu 20.04 , launching the last appimage 

![image](https://github.com/spieglt/FlyingCarpet/assets/91374123/b6625686-2801-4e3b-9c80-b412134cfa3f)

Is there a way to fix that ?

Thank you for your work !

**Comment by spieglt** [comment]
I actually just noticed that myself on Mint 20.3... not sure what happened. I just recompiled and updated the Linux binaries. Will you please try downloading [linux_flying-carpet_7.1.0_amd64.AppImage](https://github.com/spieglt/FlyingCarpet/releases/download/v7.1/linux_flying-carpet_7.1.0_amd64.AppImage) again and let me know?

**Comment by ludetie** [comment]
Hello, 

It's OK, the flying carpet is ready to fly !!
![image](https://github.com/spieglt/FlyingCarpet/assets/91374123/494f670e-c020-41e9-a106-2da0e8f0473c)

Thank you !

**Comment by spieglt** [comment]
Great to hear, thanks!
