### ISSUE TITLE
Missing Ios in peer's os 

### ISSUE THREAD

**Issue by xuancong87** [spieglt/FlyingCarpet#48]
Hi, on my macbook: 

<img width="610" alt="Screenshot 2023-07-08 at 11 35 17 AM" src="https://github.com/spieglt/FlyingCarpet/assets/138592908/b0e75cf1-6f87-4e42-8c0f-91890237f899">

And may I ask if there is any way to transfer an entire folder?

**Comment by spieglt** [comment]
Hi, try dragging and dropping a folder onto the window. You can also compress a folder to a `.zip` file or similar before sending.

**Comment by spieglt** [comment]
Oh, sorry, I missed the title. iOS and macOS can’t send to themselves or each other. Apple no longer lets you run a hotspot programmatically.

**Comment by familyfriendlymikey** [comment]
Do you happen to know of any alternatives that will allow transferring large files between ios and macos? Airdrop doesn't work for large files. SFTP on LAN works but on some connections its quite slow. It seems like it should be possible to use ftp while connected to the phone's wifi hotspot, but it didn't seem to work as expected.

**Comment by spieglt** [comment]
Why doesn't AirDrop work for large files? macOS and iOS can both use SMB, iOS via the Files app. That's probably your best bet. Just make a share on the macOS side, make sure it's on the same wireless LAN as the iPhone, and copy/paste to and from that folder.

**Comment by familyfriendlymikey** [comment]
When I try to airdrop 30GB files it usually just hangs on `sending...` or has some progress then stops.

Hmm, I imagine SMB would be subject to the same bandwidth limitation of the LAN same as SFTP, but I'll give it a shot. Thanks :)

**Comment by spieglt** [comment]
Yeah, whether you use FTP, SMB, or something else, it's always going to be subject to the speed of your LAN and the network cards on the devices.
