### ISSUE TITLE
Sending doesn't work in android 

### ISSUE THREAD

**Issue by shayan15sa** [spieglt/FlyingCarpet#49]
Hey man. Thanks for your awesome work.

Recently I installed the android version and got this error

Please restart transfer. Failed to scan QR code: com.google.mlkit.common.MlKitException: Waiting for the Barcode UI module to be downloaded.
Please restart transfer. Failed to scan QR code: com.google.mlkit.common.MlKitException: Waiting for the Barcode UI module to be downloaded.

My phone is a Samsung A33 android 13

**Comment by spieglt** [comment]
Thanks for the kind words! It really is just a matter of waiting for the barcode UI module to download, if you have a decent WiFi connection it should clear up in a few minutes. Flying Carpet uses Google Play Services' barcode scanner, though that's been a frustrating experience for this and other reasons, so you can also use the `android_FlyingCarpet_api_24.apk` version on the [releases](https://github.com/spieglt/FlyingCarpet/releases/) page which uses a different barcode scanning library if you want.

**Comment by shayan15sa** [comment]
Thank you a lot man ❤️
Hope you best
