### ISSUE TITLE
Incompatible Android Devices

### ISSUE THREAD

**Issue by Zacrain** [spieglt/FlyingCarpet#59]
Neither via the Play Store nor via directly downloading the apk an installation is possible. 

Google Play Store says the device is incompatibie. When trying to install the apk directly the package manager complains that there was an error parsing the file.

This affects at least my Xiaomi Mi A1 with Android 9 (Android One) and a Shiftphone SHIFT6mq with Android 10.

If there are good reasons that these devices are not supported, it would be good to know the requirements.

**Comment by spieglt** [comment]
Unfortunately Xiaomi devices do not seem to support Google's [LocalOnlyHotspot](https://developer.android.com/develop/connectivity/wifi/localonlyhotspot) API which is used by Flying Carpet. Please see https://github.com/spieglt/FlyingCarpet/issues/44 for a previous discussion. I'll add a note about this to the readme. Flying Carpet requires at least Android 11, which I would guess is why the Shiftphone doesn't work, though I don't know much about Shiftphone.

**Comment by spieglt** [comment]
@Zacrain I don't remember why I had to set the minimum API version to 30 (Android 11), but I just compiled it with minimum API set to 19 and it seemed to work. Please try this APK on the Shiftphone and let me know, thanks.
https://github.com/spieglt/FlyingCarpet/releases/download/v8.0.1/android_FlyingCarpet_8.0.0_minimum_SDK_19.apk

**Comment by spieglt** [comment]
@Zacrain there is a new version that requires Android 6/SDK 23, please try it and let me know if you're able.

https://github.com/spieglt/FlyingCarpet/releases/download/v8.0.1/android_FlyingCarpet_8.0.1.apk
