### ISSUE TITLE
Its taking up too much disk space

### ISSUE THREAD

**Issue by Zero3K** [spieglt/FlyingCarpet#6]
86 MB seems to be high for what it does. Is there any way to reduce it or not?

**Comment by spieglt** [comment]
Yeah, the CLI version is only around 4MB. Not unless you know of a better GUI library for Go than github.com/dontpanic92/wxGo. When I used Electron it was around half a gig.... I should probably just rewrite this in C++ someday but that will take a while.

**Comment by Zero3K** [comment]
I'll look into it soon.

**Comment by Zero3K** [comment]
Please take a look at the list of GUIs that are in https://github.com/avelino/awesome-go#gui.

**Comment by spieglt** [comment]
I've reviewed that list before. None are a better option for Mac/Windows/Linux as far as I can tell.
