### ISSUE TITLE
Necessary version of glibc not available

### ISSUE THREAD

**Issue by ninalanyon** [spieglt/FlyingCarpet#63]
I downloaded the deb and installed it.  When I run flying carpet I get the following error:

```
$ flying-carpet 
flying-carpet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by flying-carpet)
flying-carpet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by flying-carpet)
flying-carpet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by flying-carpet)

```
I have 2.31 on Linux Mint 20.3
Is there an easy fix?

**Comment by spieglt** [comment]
Hmm sorry, I thought I'd compiled that version on Mint 20.3 but now that I think about it it might have been Mint 21. Are you able to use the AppImage version?

**Comment by ninalanyon** [comment]
I daresay I could use the AppImage.  I just prefer to stick with one way of installing things.  I'll give it a try.  Thanks for the quick response.

**Comment by spieglt** [comment]
Dang, okay, thanks for trying. Guess I'll have to install an older Mint or Ubuntu version, may take a bit.

**Comment by spieglt** [comment]
Please try [linux_flying-carpet_8.0.1_amd64_glibc2.31.deb](https://github.com/spieglt/FlyingCarpet/releases/download/v8.0.1/linux_flying-carpet_8.0.1_amd64_glibc2.31.deb) and let me know.

**Comment by ninalanyon** [comment]
It worked.
Thanks.

**Comment by spieglt** [comment]
Awesome, thanks for following up!
