### ISSUE TITLE
Win10 <--> Android wont correct work.

### ISSUE THREAD

**Issue by freedomforwhat** [spieglt/FlyingCarpet#66]
Greetings! First of all, I would like to thank you very much for creating this kind of application, because I have long wanted to transfer files between my win and android devices, using the full power (speed) of wifi connection.

I had a few mishaps while trying to use your wonderful development. They are listed below:
1) apk file on my device NOT with minimum sdk, exactly what weighs 10.3mb, unfortunately, could not be installed (just a package installation error). Like the version with gPlay, my device (according to GP assurances) is not supported.
[installing apk v8 minimum sdk 19 SUCCEEDED.]

2) running the .exe on win10 succeeded, selected send, peer's os - android, selected the file from a serviceable usb stick, clicked Start Transfer. On android selected receive, selected win os, selected folder, scanned qr code on PC, waited until correct network name was displayed on android, clicked connect, saw "connected" notification pop up and got the app FLYING, just saw my desktop of my mobile device.

Unfortunately sending and receiving back and forth from android to PC was not successful either. And .msi instead of .exe get failure also, instead of sending or receiving the file successfully I get exit to the desktop of my mobile device (Android).

My android device: oukitel wp9, android ver 10. The shell (firmware), as far as I know, is standard, I have not modified.

I hope this information will help you to make your product even more perfect! 
I would like to add a wish that a new wifi hotspot is not created, but uses the network to which both devices are connected. Thank you!

**Comment by spieglt** [comment]
Thank you for the kind words! And thanks for trying the minimum SDK 19 version, unfortunately the others don't require Android 11 or above. So the Android version is crashing... I'm not sure why that would be offhand and unfortunately I don't have crash logs built in. I also don't have a device with Android 10 so can't test myself. I'll think about this one.

> I would like to add a wish that a new wifi hotspot is not created, but uses the network to which both devices are connected. Thank you!
This would be a large addition to what this project does and is this need is already addressed by a lot of other projects. I'll probably keep Flying Carpet hotspot-only.

**Comment by spieglt** [comment]
I haven't come up with a good solution yet. It might be a while before I can get a device that runs Android 10 or build in better crash reporting. If you are willing and able to send me a bug report from the Android phone, please follow [these steps](https://developer.android.com/studio/debug/bug-report) and email the file to theron@spiegl.dev.

**Comment by spieglt** [comment]
@freedomforwhat there is a new version that requires Android 6/SDK 23, please try it and let me know if you're able.

https://github.com/spieglt/FlyingCarpet/releases/download/v8.0.1/android_FlyingCarpet_8.0.1.apk

**Comment by freedomforwhat** [comment]
Tried 8.0.1.apk and after several futile attempts got this, but not the file, unfortunately.ANDROID:
```Joining flyingCarpet_49b7.

Starting Transfer
Failed to connect to hotspot
Joining flyingCarpet_6ad9
No files selected.
Joining flyingCarpet_6ad9

Starting Transfer
Joining flyingCarpet_6ad9

Starting Transfer
Disconnected from hotspot
Disconnected from hotspot
Disconnected from hotspot
Transfer error: failed to connect to /192.168.137.1 (port 3290) from /:: (port 60666): connect failed: ECONNABORTED (Software caused connection abort)

Transfer error: failed to connect to /192.168.137.1 (port 3290) from /:: (port 60672): connect failed: ECONNABORTED (Software caused connection abort)

Failed to connect to hotspot
```

The application on the PC is the same version, haven't installed anything new. PC:
```
Welcome to Flying Carpet!

Start the transfer on the other device and scan the QR code when prompted.
Waiting for permission to add firewall rule, please see UAC prompt in your taskbar.
Added firewall rule
Hosted network flyingCarpet_49b7 has started
Waiting for connection...
Transfer cancelled

Start the transfer on the other device and scan the QR code when prompted.
Waiting for permission to add firewall rule, please see UAC prompt in your taskbar.
Added firewall rule
Waiting for connection...
Hosted network flyingCarpet_6ad9 has started
```
Maybe problem in my laptop..

**Comment by freedomforwhat** [comment]
@spieglt Note: at the same moment the laptop is connected to the router via Ethernet wire.

**Comment by spieglt** [comment]
Hmm, from the output it looks to me like the laptop is working correctly. The Android output is strange though. Did you maybe hit the button multiple times before the transfer started?
