### ISSUE TITLE
Release APK on F-Droid?

### ISSUE THREAD

**Issue by tsilvs** [spieglt/FlyingCarpet#67]

**Comment by spieglt** [comment]
Hi, a couple people have brought this up but the source code for the Android version is not public, so as I understand it it's not eligible for F-Droid currently. I'm considering making the code public.

**Comment by spieglt** [comment]
@tsilvs the Android version is now in the repo

**Comment by spieglt** [comment]
It's now in F-Droid: https://f-droid.org/en/packages/dev.spiegl.flyingcarpet/
