### ISSUE TITLE
can't run on win7 sp1

### ISSUE THREAD

**Issue by Donald2010** [spieglt/FlyingCarpet#68]
install successfully on win7, but when run , the window popup, content not shown and then dissapear, program quit quietly. 

I have run orange application  which also uses tauri for gui on this machine.

**Comment by spieglt** [comment]
I tried to run FlyingCarpet.exe in a Windows 7 VM and got an error saying `The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll`. Apologies, but Windows 7 is four years past its end of life date and I don't plan on supporting it.
