### ISSUE TITLE
Ios ipa file share

### ISSUE THREAD

**Issue by Anlimia** [spieglt/FlyingCarpet#69]
You have uploaded the android apk, but why not share the ios ipa file? So that you can bypass the appstore

**Comment by spieglt** [comment]
How would you sideload an iOS app? I'm not aware of a good way to install it.

**Comment by Anlimia** [comment]
The current way is trollstore, but we must not forget jb and sideloadly

**Comment by spieglt** [comment]
Apologies, but I don't think this is something I'm going to provide as Apple doesn't officially support sideloading.

**Comment by jpgjm** [comment]
I would also like the ipa to be released on GitHub.

Sideloading apps does not require jailbreaking the device, making it easy for users.

You can sideload apps in the following ways:
・[AltStore](https://github.com/altstoreio/AltStore)
・[SideStore](https://github.com/SideStore/SideStore)
・[Impactor](https://github.com/khcrysalis/Impactor)
・[iloader](https://github.com/nab138/iloader)
・Sideloadly
・[StikStore](https://stikstore.app/#features)
