### ISSUE TITLE
Context menu entry on all file types

### ISSUE THREAD

**Issue by Zero3K** [spieglt/FlyingCarpet#7]
It would be nice if it could set a context menu entry on all file types that would have one or more of them be sent via Flying Carpet.

**Comment by spieglt** [comment]
Not sure how doable this is with it being a Go project/the current GUI framework but will look into it.

**Comment by Zero3K** [comment]
Maybe you could include CLI support into the GUI version.

**Comment by spieglt** [comment]
The CLI version is on the releases page, though I don't think that makes context menu integration any easier unfortunately. That will have to be a C++/Windows API interaction I believe.
