### ISSUE TITLE
ios app don't transfer heif pictures 

### ISSUE THREAD

**Issue by gael-api** [spieglt/FlyingCarpet#78]
Hi, Thanks for this wonderful app!
There's an issue with the iOS app v8.0.1 on **iOS 17.5.1**

Some pictures can't be transferred. I track them down and see that's the HEIF ones. 
The following message appears in FlyingCarpet : `Error: could not get filename from path.`

When I choose the most compatible format from the camera roll options, it works like a charm with my **Fedora 40 Linux** laptop.

**Comment by spieglt** [comment]
Hmm, sorry to hear that. A friend noticed the same bug with HEIC live photos when the iOS version first came out, so I added a block like:
```
// if it's a live photo, use the jpeg representation
let fileType = result.itemProvider.hasItemConformingToTypeIdentifier(UTType.heic.identifier)
    ? UTType.jpeg.identifier
    : UTType.item.identifier
```
I assume I just need the same for `UTType.heif.identifier` or some such. I'll make an update when I get some time. Thanks for letting me know!

**Comment by spieglt** [comment]
These are photos, not videos?

**Comment by gael-api** [comment]
Only the HEIF photos. Videos transfer works well.

**Comment by spieglt** [comment]
Version 8.0.2 should be available in the App Store, please try updating and let me know.

**Comment by gael-api** [comment]
With v8.0.2, heif files are correctly converted to jpeg files if **Automatic  Format** is selected in CameraRoll options.
But there's still the error if the native format option is choosen.

**Comment by spieglt** [comment]
Can you please send more information or a screenshot of this setting? I only see this in Camera > Format:
![image](https://github.com/spieglt/FlyingCarpet/assets/22626146/c4cb8032-c674-4292-8ef1-f75dfd3a3e66)

**Comment by spieglt** [comment]
Ah, you mean this, when `Options` is selected after choosing the photos from Camera Roll. Unfortunately I couldn’t get the HEIC/HEIF photos to work, so sending them as JPEGs is the intended workaround. 
![image](https://github.com/spieglt/FlyingCarpet/assets/22626146/8f3d8eab-c6ce-4a73-bfa0-f76fb53c596c)

**Comment by gael-api** [comment]
Yes, it's the parameter I was referring to.
If HEIF pictures aren't transferable, it's ok for me.
