### ISSUE TITLE
Android Client 'WifiService' Error - can't send or receive

### ISSUE THREAD

**Issue by jh043** [spieglt/FlyingCarpet#79]
It shows: 'WifiService: Neither user 10192 nor current process has android.permission.ACCESS_WIFI_STATE.'
![2391718688951_ pic](https://github.com/spieglt/FlyingCarpet/assets/79069439/4fbfd46f-149d-4d12-95bb-20b8054033e3)

[My Phone info.]
Vivo Y31s
Funtouch OS 10.5, based on Android 11
required permission: Location, already given.

**Comment by spieglt** [comment]
Hi, sorry, I don't know much about Vivo or Funtouch OS, but if it's an operating system that doesn't allow accessing the WiFi state, Flying Carpet probably doesn't work on that device.
