### ISSUE TITLE
Error starting TCP connection: Connection refused (os error 61)

### ISSUE THREAD

**Issue by adamlogan** [spieglt/FlyingCarpet#86]
I was testing sending a PNG file from my 2021 MacBook Pro
14-inch, M1 Pro to my Android phone, a Pixel 7A. I kept getting OS Error (61).

On Android Phone:
I tried disabling Adguard on the Android phone (as it has a firewall feature), and turned off private DNS as well.
I changed hotspot from 5 ghz to 2.4 ghz based on another thread I saw on here saying flying carpet does not support 5 ghz.
I checked for built-in firewall, afaik, there isn't one I have access to?

On MacOS M1 Mabook Pro:
• I disabled adguard.
• I disabled Little Snitch.
• I added a rule in MacOS built-in App firewall to allow inbound connections to Flying Carpet (I selected the app).
• I added Flying Carpet to permission for **Full Disk Access**. The file I am trying to share is on the Desktop. 
Flying Carpet for MacOS should add functions to check and request permissions to access specific **Files and Folders** MacOS protected directories which include: Desktop, Documents, Downloads, Pictures, Movies, Music, Mail, Calendars, Contacts, Reminders. Diligence advised on what makes sense to request permissions for. Should definitely make it optional for users which permissions to give.

Even after manually adding Full Disk Access for Flying Carpet which I really would not have to do, but since MacOS does not provide a way to manually add apps to Files & Folders afaik this is something the dev has to build into the app somehow, I have no other choice, I am still getting that error.

Consider this a feature request for permissions functions, and also an issue because I still can't send from MacOS to Android despite what I've tried.

**Comment by spieglt** [comment]
Which side said OS Error (61), the Mac? Please paste the full output of both sides. You should not have to modify disk permissions to address a TCP error. The Android device should be hosting the hotspot, so if the Mac is complaining that the connection is being refused, it sounds like the Android isn’t listening for a connection when it should be. But I’ll need full outputs to diagnose.

Once I finish the Bluetooth functionality, the  macOS version will be written natively in Swift which should mean less friction with permissions and such. But no changes will be made to the current macOS version before then.

**Comment by adamlogan** [comment]
The Mac, yes.

I figured it out.

I didn't realize Flying Carpet handled the wifi configuration to start a hotspot with unique SSID and password.

I had been manually enabling hotspot mode on my phone, connecting, and then trying to initiate the transfer.

Would be good to have a tip with the error to explain what the error means and some potential solutions and this (my guess is) common misunderstanding.

**Comment by spieglt** [comment]
Great to hear, thanks for following up. You're not the first person recently to think they had to set up the hotspot themselves so I do need to include some more detailed instructions, hope to do that for the next version.
