### ISSUE TITLE
Win10 -> Win10 cannot connect

### ISSUE THREAD

**Issue by frozenduck** [spieglt/FlyingCarpet#87]
When I try to connect to the FlyingCarpet network always says wrong pin, even if I copy it.

**Comment by spieglt** [comment]
Paste the output of both sides of the failed transfer please.

**Comment by frozenduck** [comment]
Sorry, it's my mistake, for some reason I thought it was necessary to connect to flyingCarpet's wifi network and enter the code there. If just enter the code in the app and don't touch the networks, everything is fine, I was able to transfer the files.

**Comment by spieglt** [comment]
Great to hear, thanks for following up.
